import javax.swing.*;
import java.awt.*;

/**
 * Created by vatomouro1 on 2/1/2017.
 */
class SingleMultiGui {

    private JFrame singleMultiGuiFrame;
    private JButton singleButton;
    private JButton multiButton;
    private JPanel singleMultiGuiPanel;
    private JLabel selectGameTypeLabel;

    public SingleMultiGui() {
        singleMultiGuiFrame = new JFrame("APORTHITO");            //στον κατασκευαστη δημιουργουμε το γραφικο μας περιβαλλον

        $$$setupUI$$$();
        singleMultiGuiFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        singleMultiGuiFrame.setSize(700, 500);
        singleMultiGuiFrame.setLocationRelativeTo(null);
        singleMultiGuiFrame.setVisible(true);
        singleMultiGuiFrame.setContentPane(singleMultiGuiPanel);

        setSingleButtonAction();                                      //και καλουμε τις μεθοδους που ενεργοποιουν τα κουμπια μας
        setMultiButtonAction();
    }

    private void setSingleButtonAction() {

        singleButton.addActionListener(ae -> {                 //Αν επιλεγει το κουμπι του μονου παιχνιδιου
            singleMultiGuiFrame.setVisible(false);              //εξαφανιζουμε το παραθυρο
            SinglePlayerMode spl = new SinglePlayerMode();      // και καλουμε τη μεθοδο που εκκινει το μονο παιχνιδι
            spl.startSinglePlayerMode();
        });
    }

    private void setMultiButtonAction() {

        multiButton.addActionListener(ae -> {
            singleMultiGuiFrame.setVisible(false);         //το ιδιο συμβαινει και στο κουμπι του διπλου αντιστοιχα
            MultiPlayerMode mpl = new MultiPlayerMode();
            mpl.srartMultiPlayerMode();
        });
    }

    protected void setButtonTextLanguage(String single, String multi, String selectLabel) {
        singleButton.setText(single);                           //αυτη ειναι μεθοδος που καλειται απο μεθοδο της κλασης Language
        multiButton.setText(multi);                              //για να δωσει κειμενο στη σωστη γλωσσα στα κουμπια μας
        selectGameTypeLabel.setText(selectLabel);
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        singleMultiGuiPanel = new JPanel();
        singleMultiGuiPanel.setLayout(new GridBagLayout());
        singleMultiGuiPanel.setBackground(new Color(-10328710));
        singleMultiGuiPanel.setForeground(new Color(-10328710));
        singleButton = new JButton();
        singleButton.setBackground(new Color(-15332589));
        singleButton.setForeground(new Color(-16551924));
        singleButton.setText("Button");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 50;
        gbc.ipady = 20;
        singleMultiGuiPanel.add(singleButton, gbc);
        multiButton = new JButton();
        multiButton.setBackground(new Color(-15332589));
        multiButton.setForeground(new Color(-16551924));
        multiButton.setText("Button");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 50;
        gbc.ipady = 20;
        singleMultiGuiPanel.add(multiButton, gbc);
        selectGameTypeLabel = new JLabel();
        selectGameTypeLabel.setFont(new Font("Corbel", Font.PLAIN, 24));
        selectGameTypeLabel.setForeground(new Color(-15332589));
        selectGameTypeLabel.setText("Select Game Type");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        singleMultiGuiPanel.add(selectGameTypeLabel, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return singleMultiGuiPanel;
    }
}
